"""remove table userordertotal and edit status column of orders table to be isAccepted

Revision ID: 01a07750bb44
Revises: cb36061ebf77
Create Date: 2021-05-06 14:52:53.417001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a07750bb44'
down_revision = 'cb36061ebf77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userOrderTotal')
    op.add_column('orders', sa.Column('isAccepted', sa.Boolean(), server_default='false', nullable=True))
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'isAccepted')
    op.create_table('userOrderTotal',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"userOrderTotal_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('order_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name='userOrderTotal_cart_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='userOrderTotal_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='userOrderTotal_pkey')
    )
    # ### end Alembic commands ###
