"""add product-name and product picture to cart table

Revision ID: 3738ee747e0e
Revises: 1ded1c042d0b
Create Date: 2021-05-06 02:48:42.384944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3738ee747e0e'
down_revision = '1ded1c042d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('pizza_name', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('product_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'product_picture')
    op.drop_column('cart', 'pizza_name')
    # ### end Alembic commands ###
