"""update cart

Revision ID: 38933a35100d
Revises: 764f1d8791a2
Create Date: 2021-05-06 13:44:00.176984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38933a35100d'
down_revision = '764f1d8791a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'product_picture')
    # ### end Alembic commands ###
