"""update cart delete product_name

Revision ID: 3d93a5e5f371
Revises: 8af6c0eaef8d
Create Date: 2021-05-06 03:11:33.070663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d93a5e5f371'
down_revision = '8af6c0eaef8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'product_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_name', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
