"""add userOrderTotal table

Revision ID: 764f1d8791a2
Revises: 1cdf1aa5d1fd
Create Date: 2021-05-06 13:43:12.195301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764f1d8791a2'
down_revision = '1cdf1aa5d1fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'product_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
