"""update cart add product column

Revision ID: 9903134358c6
Revises: 3d93a5e5f371
Create Date: 2021-05-06 03:12:34.040365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9903134358c6'
down_revision = '3d93a5e5f371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'product')
    # ### end Alembic commands ###
