"""remove product-price from products table

Revision ID: b828450dbc33
Revises: ef162c7d2fe8
Create Date: 2021-05-06 11:06:26.685240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b828450dbc33'
down_revision = 'ef162c7d2fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'product_price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('product_price', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
