"""edit cart table update product name

Revision ID: d688fb8b3505
Revises: 3738ee747e0e
Create Date: 2021-05-06 02:51:55.046613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd688fb8b3505'
down_revision = '3738ee747e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_name', sa.Integer(), nullable=True))
    op.drop_column('cart', 'pizza_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('pizza_name', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cart', 'product_name')
    # ### end Alembic commands ###
